name: Javascript unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
  pull_request:
    paths:
      - 'web/html/src/**'

jobs:
  javascript_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn --cwd susemanager-frontend install --frozen-lockfile

    - name: Run tests
      run: yarn --cwd web/html/src test --no-cache
      env:
        BABEL_ENV: 'test'
