name: Javascript unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
  pull_request:
    paths:
      - 'web/html/src/**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn test
      env:
        BABEL_ENV: 'test'