name: OSC build

on:
  push:
    branches:
      - master
    # paths:
    #   - 'web/html/src/**'
  pull_request:
    # paths:
    #   - 'web/html/src/**'

jobs:
  web_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install OSC
      run: sudo apt-get install -y osc

    - name: Run build
      working-directory: ./web
      run: osc build
      # TODO: Can we have a public account with only readonly access to enough things to make this work?
      # Alternatively, we can remove the pull_request hook and use repo secrets
      # See
      #  - https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md
      #  - https://docs.github.com/en/actions/security-guides/encrypted-secrets
